In [4]:
import time
import numpy as np

# Create large Python list and NumPy array
large_list =[2,8,2,4,2,1,7,8,6,9,4,5,2,54,6,21,5,4,6,4,65,2,54,89,5,2,17,2,21,5,6,5,5,1,52]  # Approx 1M elements
large_array = np.array(large_list)

# Time Python list sum
start_time = time.time()
sum_list = sum(large_list)
python_time = time.time() - start_time

# Time NumPy array sum
start_time = time.time()
sum_array = np.sum(large_array)
numpy_time = time.time() - start_time

print("Python list sum time:", python_time, "seconds")
print("NumPy array sum time:", numpy_time, "seconds")

Python list sum time: 6.270408630371094e-05 seconds
NumPy array sum time: 0.00011777877807617188 seconds


In [3]:
import numpy as np

var1=np.array([[[1,2],[1,2]],[[1,2],[1,2]]])
var1
var1.shape   

(2, 2, 2)

#what is numpy?

#NumPy (short for Numerical Python) is an open-source Python library that provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.

#It is one of the core libraries for scientific computing in Python and is heavily used in data science, machine learning, and numerical analysis.
#Key Features of NumPy:

    

In [17]:
var2=np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
print(var2)
var2.shape




[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]


(2, 2, 3)

In [10]:
#1D Array (One-dimensional Array)
#A 1D array is just a linear collection of values.
import numpy as np
array_1d = np.array([[[1, 2, 3],[1, 2, 3],[1, 2, 3]],[[1, 2, 3],[1, 2, 3],[1, 2, 3]]])
print("1D Array:")
print(array_1d)
#array_1d.ndim  #we will use ndim to find the dimensions of the particular array 
array_1d.shape

1D Array:
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]]


(2, 3, 3)

In [20]:
#2D Array (Two-dimensional Array)
#A 2D array is like a table or matrix with rows and columns.
# Creating a 2D array (matrix)
array_2d = np.array([[1, 2, 3], [4, 5,3],[2,5,7]])
print("\n2D Array:")
print(array_2d)
array_2d.ndim
array_2d.shape


2D Array:
[[1 2 3]
 [4 5 3]
 [2 5 7]]


(3, 3)

In [19]:
#3D Array (Three-dimensional Array)
#A 3D array is a collection of 2D arrays (matrices). You can think of it as a "stack" of matrices.
# Creating a 3D array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]],[[2,5],[5,8]]])
print("\n3D Array:")
print(array_3d)
#array_3d.ndim
array_3d.shape


3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]

 [[2 5]
  [5 8]]]


(3, 2, 2)

In [33]:
#Arithmetic Operations
#Creating two NumPy arrays
arr1 = np.array([[10, 20,8,3],[10, 20,8,3]])
arr2 = np.array([1, 2, 3,5])

# Addition
add_result = arr1 + arr2  # [10+1, 20+2, 30+3, 40+4]
print("Addition:", add_result)

# Subtraction
sub_result = arr1 - arr2  # [10-1, 20-2, 30-3, 40-4]
print("Subtraction:", sub_result)

# Multiplication
mul_result = arr1 * arr2  # [10*1, 20*2, 30*3, 40*4]
print("Multiplication:", mul_result)

# Division
div_result = arr1 / arr2  # [10/1, 20/2, 30/3, 40/4]
print("Division:", div_result)

Addition: [[11 22 11  8]
 [11 22 11  8]]
Subtraction: [[ 9 18  5 -2]
 [ 9 18  5 -2]]
Multiplication: [[10 40 24 15]
 [10 40 24 15]]
Division: [[10.         10.          2.66666667  0.6       ]
 [10.         10.          2.66666667  0.6       ]]


In [34]:
arr1 = np.array([[10, 20,8,3],[10, 20,8,3]])
var4=arr1+3
var4

array([[13, 23, 11,  6],
       [13, 23, 11,  6]])

In [63]:
#reshaping 1d array to 2 and 3 d array 

var1=np.array([1,2,3,4,5,6])
var2=var1.reshape(2,3,1)

# reshaping 2d insto 1 and 3 
var3=np.array([[1,2,3],[1,2,3]])
var4=var3.reshape(1,3,2)

#reshaping 3d into 1 and 2 d
var5=np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
var6=var5.reshape(4,3)
var6

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [49]:
#NumPy Arithmetic Functions
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

print("Addition:", np.add(arr1, arr2))  # [6 8 10 12]
print("Subtraction:", np.subtract(arr1, arr2))  # [-4 -4 -4 -4]
print("Multiplication:", np.multiply(arr1, arr2))  # [5 12 21 32]
print("Division:", np.divide(arr1, arr2))  # [0.2 0.333 0.428 0.5]

Addition: [ 6  8 10 12]
Subtraction: [-4 -4 -4 -4]
Multiplication: [ 5 12 21 32]
Division: [0.2        0.33333333 0.42857143 0.5       ]


In [5]:
#Reshaping 1D Array into 2D
#You can reshape a 1D array into a 2D array (e.g., a row or column vector
# Original 1D array
import numpy as np
array_1d = np.array([1, 2, 3, 4,5,6])
# Reshaping to 2D (2 rows, 3 columns)
array_2d = array_1d.reshape(2,1,3)
print("Reshaped to 2D (2x3):")
print(array_2d)


Reshaped to 2D (2x3):
[[[1 2 3]]

 [[4 5 6]]]


In [34]:
#Reshaping a 1D Array to a 3D Array
#We will begin with a 1D array and reshape it to a 3D array.
# Original 1D array with 12 elements
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# Reshaping to a 3D array (2 layers, 2 rows, 3 columns)
array_3d = array_1d.reshape(4, 1, 3)

print("Reshaped to 3D (2x2x3):")
print(array_3d)


Reshaped to 3D (2x2x3):
[[[ 1  2  3]]

 [[ 4  5  6]]

 [[ 7  8  9]]

 [[10 11 12]]]


'Explanation:\n\n    The original 1D array has 12 elements: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12].\n    By reshaping it to (2, 2, 3), we get:\n        2 layers (depth),\n        2 rows in each layer, and\n        3 columns in each row.'

In [2]:
#2. Reshaping a 3D Array to a Different Shape
# Original 3D array (2x2x3)
import numpy as np
array_3d = np.array([[[1, 2, 3], [4, 5, 6]],
                     [[7, 8, 9], [10, 11, 12]]])   # 2,2,3

# Reshaping the 3D array to (3 layers, 2 rows, 2 columns)
reshaped_array = array_3d.reshape(6,2)

print("\nReshaped to 3D (3x2x2):")
print(reshaped_array)




Reshaped to 3D (3x2x2):
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [16]:
#reshaping from 1D to 2D
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)  # Reshape into 2 rows and 3 columns
print(reshaped_arr)



[[1 2 3]
 [4 5 6]]


In [3]:
#Reshaping a 2D Array into a 1D Array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
flattened_arr = arr2d.reshape(6)  # Converts 2D into 1D
print(flattened_arr)

[1 2 3 4 5 6]


In [6]:
#Adding a Row to a 2D Array
import numpy as np 
arr2d = np.array([[1, 2, 3], [4, 5, 6],[4, 5, 6]])
new_arr2d = np.append(arr2d, [[7],[8], [9]],axis=1)#(var name,value,axis)
print(arr2d)
print(new_arr2d)



[[1 2 3]
 [4 5 6]
 [4 5 6]]
[[1 2 3 7]
 [4 5 6 8]
 [4 5 6 9]]


In [13]:
#Adding a Column to a 2D Array
#new_col = np.array([[10], [20]])  # New column
new_arr2d = np.append(arr2d, [[10], [20]], axis=1)
print(new_arr2d)




[[ 1  2  3 10]
 [ 4  5  6 20]]


In [9]:
#Sorting in NumPy
#NumPy provides np.sort() for sorting arrays.
#Sorting a 1D Array
arr = np.array([40, 10, 50, 20, 30])
sorted_arr = np.sort(arr)
print(sorted_arr)




[10 20 30 40 50]


In [7]:
#Sorting a 2D Array Row-wise
import numpy as np
arr2d = np.array([[3, 2, 1], [1, 1, 4],[3,9,8]])
sorted_arr2d = np.sort(arr2d, axis=0)
print(arr2d,"\n")
print(sorted_arr2d)

#3,2,1
#1,1,4
#3,9,8



[[3 2 1]
 [1 1 4]
 [3 9 8]] 

[[1 1 1]
 [3 2 4]
 [3 9 8]]


In [10]:
#Sorting a 2D Array Column-wise
import numpy as np
arr2d = np.array([[3, 2, 1], [1, 1, 4],[3,9,8]])
sorted_arr2d = np.sort(arr2d, axis=1)
print(sorted_arr2d)


[[3 2 1]
 [4 1 1]
 [9 8 3]]


In [9]:
# sorting in descending order
import numpy as np

# Example 2D array
arr = np.array([[3, 1, 4], [1, 5, 9], [2, 6, 5]])

# Sort each row (axis=1) in descending order
sorted_arr = np.sort(arr, axis=1)[:, ::-1]

print("Sorted rows (descending, axis=1):")
print(sorted_arr)

Sorted rows (descending, axis=1):
[[4 3 1]
 [9 5 1]
 [6 5 2]]


In [4]:
# sort row or colunm on particukar index
import numpy as np
arrayyy = np.array([[3, 1, 4], [1, 5, 9], [2, 6, 5]])
arrayyy[:,0].sort()
arrayyy

array([[1, 1, 4],
       [2, 5, 9],
       [3, 6, 5]])

In [28]:
#Deleting Elements in NumPy
#NumPy provides the np.delete() function to remove elements from an array. This does not modify the original array but returns a new one.
#np.delete(array, index, axis)

arr = np.array([10, 20, 30, 40, 50])
new_arr = np.delete(arr,1)  # Deleting element at index 2 (30)
print(new_arr)

[10 30 40 50]


In [10]:
#Deleting a Row from a 2D Array
arr2d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 10]],[[1, 25, 3], [4, 15, 6], [7, 8, 110]]])
new_arr2d = np.delete(arr2d,(1,0,0), axis=1)  # Deleting row at index 1
print(arr2d,"\n")
print(new_arr2d)

[[[  1   2   3]
  [  4   5   6]
  [  7   8  10]]

 [[  1  25   3]
  [  4  15   6]
  [  7   8 110]]] 

[[[  7   8  10]]

 [[  7   8 110]]]


In [7]:
array=np.array([1,2,3,4,5])
array[4]=100
print(array)
array1=np.array([[1,2,3],[3,4,5]])
array1[1,2]=200
print(array1)

[  1   2   3   4 100]
[[  1   2   3]
 [  3   4 200]]


In [24]:
#Deleting a Column from a 2D Array
new_arr2d = np.delete(arr2d, 1, axis=1)  # Deleting column at index 1
print(new_arr2d)

[[1 3]
 [4 6]
 [7 9]]


In [25]:
#Adding Elements in NumPy
#Using np.append()
#np.append(array, values, axis)
#Example: Adding Elements to a 1D Array
arr = np.array([10, 20, 30])
new_arr = np.append(arr, [[40, 50]])
print(new_arr)
'''NumPy's np.append() flattens the input before appending. It treats [[[40, 50]]] as just [40, 50] internally.

Explanation:
The triple brackets [[[40, 50]]] create a nested structure, but np.append() does not care about nesting.
np.append() flattens [[[40, 50]]] to just [40, 50] and appends it to arr.
This is why it works fine, and the output is [10, 20, 30, 40, 50].
'''

[10 20 30 40 50]


"NumPy's np.append() flattens the input before appending. It treats [[[40, 50]]] as just [40, 50] internally.\n\nExplanation:\nThe triple brackets [[[40, 50]]] create a nested structure, but np.append() does not care about nesting.\nnp.append() flattens [[[40, 50]]] to just [40, 50] and appends it to arr.\nThis is why it works fine, and the output is [10, 20, 30, 40, 50].\n"

In [32]:
#Vectors in NumPy
#A vector is a 1D NumPy array that represents a mathematical vector.
#Creating a Vector
vector = np.array([1, 2, 3, 4])
print(vector)


#Vector Addition
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
result = v1 + v2  # Element-wise addition
print(result)

[1 2 3 4]
[5 7 9]


In [31]:
#Using NumPy for Dot Product
#Dot Product of 1D Arrays (Vectors)

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

dot_product = np.dot(A, B)  # OR A @ B
print("Dot Product:", dot_product)  # Output: 1*4 + 2*5 + 3*6 = 32

#Dot Product of 2D Arrays (Matrix Multiplication)
#For matrices, np.dot() performs matrix multiplication (not element-wise multiplication).

M1 = np.array([[1, 2], [3, 4]])
M2 = np.array([[5, 6], [7, 8]])

dot_matrix = np.dot(M1, M2)  # OR M1 @ M2
print("Matrix Dot Product:\n", dot_matrix)



Dot Product: 32
Matrix Dot Product:
 [[19 22]
 [43 50]]


'Calculation:\n[1234]⋅[5678]=[(1∗5+2∗7)(1∗6+2∗8)(3∗5+4∗7)(3∗6+4∗8)]=[19224350]\n[13\u200b24\u200b]⋅[57\u200b68\u200b]=[(1∗5+2∗7)(3∗5+4∗7)\u200b(1∗6+2∗8)(3∗6+4∗8)\u200b]=[1943\u200b2250\u200b]'

In [34]:
#Scalar Operations on NumPy Arrays
#You can apply arithmetic operations between an array and a scalar, which applies the operation to every element.

#Scalar Operations
arr = np.array([5, 10, 15, 20])

# Adding a scalar
print("Add 5:", arr + 5)  # [10, 15, 20, 25]

# Subtracting a scalar
print("Subtract 3:", arr - 3)  # [2, 7, 12, 17]

# Multiplying by a scalar
print("Multiply by 2:", arr * 2)  # [10, 20, 30, 40]

# Dividing by a scalar
print("Divide by 5:", arr / 5)  # [1. 2. 3. 4.]
#Exponentiation and Modulo
arr = np.array([2, 3, 4])

# Exponentiation (Power)
print("Power of 2:", arr ** 2)  # [2^2, 3^2, 4^2] → [4, 9, 16]

# Modulo (Remainder)
print("Modulo 2:", arr % 2)  # [2%2, 3%2, 4%2] → [0, 1, 0]


Add 5: [10 15 20 25]
Subtract 3: [ 2  7 12 17]
Multiply by 2: [10 20 30 40]
Divide by 5: [1. 2. 3. 4.]
Power of 2: [ 4  9 16]
Modulo 2: [0 1 0]


In [35]:
#Scalar in NumPy
#In NumPy, a scalar is a 0-dimensional array, meaning it contains only a single value.

#Creating a Scalar in NumPy

scalar = np.array(10)  # A scalar NumPy array
print(scalar)  # Output: 10
print(scalar.shape)  # Output: ()  (0-dimensional)
print(scalar.ndim)  # Output: 0 (0D array)

#Scalar Operations with NumPy Arrays
#Scalars can be used to perform element-wise operations on NumPy arrays.

#Multiplying an Array by a Scalar
arr = np.array([1, 2, 3, 4, 5])
result = arr * 2  # Each element is multiplied by the scalar 2
print(result)

#Scalar Addition
arr = np.array([10, 20, 30])
result = arr + 5  # Adding scalar value to each element
print(result)
'''
Why Use Scalars in NumPy?
Scalars are faster and efficient for mathematical operations.
They are used in broadcasting when performing arithmetic operations on arrays.
They help in element-wise transformations in machine learning and data science.'''

10
()
0
[ 2  4  6  8 10]
[15 25 35]


'\nWhy Use Scalars in NumPy?\nScalars are faster and efficient for mathematical operations.\nThey are used in broadcasting when performing arithmetic operations on arrays.\nThey help in element-wise transformations in machine learning and data science.'

In [38]:
#Indexing in NumPy

#Indexing is used to access individual elements in an array.
#(a) Indexing in 1D Array
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])   # Output: 10
print(arr[2])   # Output: 30
print(arr[-1],"\n")  # Output: 50 (Negative index refers from the end)
#(b) Indexing in 2D Array

arr2D = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]])

print(arr2D[0, 0])  # Output: 1 (First row, first column)
print(arr2D[1, 2])  # Output: 6 (Second row, third column)
print(arr2D[-1, -1],"\n") # Output: 9 (Last row, last column)
#(c) Indexing in 3D Array

arr3D = np.array([[[1, 2, 3], [4, 5, 6]], 
                   [[7, 8, 9], [10, 11, 12]]])

print(arr3D[0, 1, 2])  # Output: 6 (First block, second row, third column)
print(arr3D[1, 0, 1])  # Output: 8 (Second block, first row, second column)



10
30
50 

1
6
9 

6
8


In [9]:
import numpy as np
arr2D = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]])

print(arr2D[1:,:])  # Output: 1 (First row, first column)
#print(arr2D[1, 2])  # Output: 6 (Second row, third column)

[[4 5 6]
 [7 8 9]]


In [6]:
import numpy as np
arr3D = np.array([[[1, 2, 3], [4, 5, 6]], 
                   [[7, 8, 9], [10, 11, 12]]])
print(arr3D)
print(arr3D[0, 1, 0])  # Output: 6 (First block, second row, third column)
#print(arr3D[1, 0, 1])  # Output: 8 (Second block, first row, second column)



[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
4


In [41]:
#Slicing in NumPy
#Slicing allows extracting sub-arrays using [start:stop:step] notation.
#(a) Slicing in 1D Array

arr = np.array([10, 20, 30, 40, 50, 60, 70])

print(arr[1:5])   # Output: [20 30 40 50] (Elements from index 1 to 4)
print(arr[:4])    # Output: [10 20 30 40] (First 4 elements)
print(arr[2:])    # Output: [30 40 50 60 70] (Elements from index 2 to end)
print(arr[::2])   # Output: [10 30 50 70] (Every second element)
print(arr[::-1],"\n")  # Output: [70 60 50 40 30 20 10] (Reversed array)
#(b) Slicing in 2D Array

arr2D = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

print(arr2D[1:, 2:])  # Output: [[ 7  8]
                       #          [11 12]] (Sub-matrix from row index 1, column index 2)
print(arr2D[:, 1:3])  # Output: [[ 2  3]
                       #          [ 6  7]
                       #          [10 11]] (All rows, columns from index 1 to 2)
print(arr2D[::2, ::2],"\n") # Output: [[ 1  3]
                        #          [ 9 11]] (Every alternate row & column)

#(c) Slicing in 3D Array

arr3D = np.array([[[1, 2, 3], [4, 5, 6]], 
                   [[7, 8, 9], [10, 11, 12]]])

print(arr3D[:, :, 1])  # Output: [[ 2  5]
                         #         [ 8 11]] (All blocks, all rows, second column)
print(arr3D[:, 1, :])  # Output: [[ 4  5  6]
                         #         [10 11 12]] (All blocks, second row, all columns)

[20 30 40 50]
[10 20 30 40]
[30 40 50 60 70]
[10 30 50 70]
[70 60 50 40 30 20 10] 

[[ 7  8]
 [11 12]]
[[ 2  3]
 [ 6  7]
 [10 11]]
[[ 1  3]
 [ 9 11]] 

[[ 2  5]
 [ 8 11]]
[[ 4  5  6]
 [10 11 12]]


In [44]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]], 
                   [[7, 8, 9], [10, 11, 12]]])

print(arr3D)
print(arr3D[1, :,1:])  

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[ 8  9]
 [11 12]]


In [41]:
import numpy as np
arr2D = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

print(arr2D[1:2,1:3])  

[[6 7]]


In [44]:
#Multidimensional Array in NumPy

#A multidimensional array is an array with more than one dimension (i.e., rows and columns). In NumPy, arrays can have 1D, 2D, 3D, or higher dimensions, enabling efficient data storage and manipulation.
#Types of Multidimensional Arrays
#1. One-Dimensional Array (1D)
#A 1D array is a simple list-like structure containing elements in a single row.

arr1D = np.array([10, 20, 30, 40])
print(arr1D)
print("Shape:", arr1D.shape,"\n")  # Output: (4,)#means it has 4 elements in a single dimension.

#2. Two-Dimensional Array (2D)
#A 2D array represents data in rows and columns, similar to a matrix or table.

arr2D = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]])
print(arr2D)
print("Shape:", arr2D.shape,"\n")  # Output: (3, 3)#Shape (3,3) means it has 3 rows and 3 columns.

#3. Three-Dimensional Array (3D)
#A 3D array consists of multiple 2D matrices stacked together, forming a cube-like structure.

arr3D = np.array([[[1, 2, 3], [4, 5, 6]], 
                   [[7, 8, 9], [10, 11, 12]]])

print(arr3D)
print("Shape:", arr3D.shape)  # Output: (2, 2, 3)

[10 20 30 40]
Shape: (4,) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3) 

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)


In [1]:
#Special Arrays in NumPy
#NumPy provides several special types of arrays for specific use cases. These include arrays filled with zeros, ones, identity matrices, random values, and more
import numpy as np 
#1. Zero Array (np.zeros())
#Creates an array filled with zeros.
zero_arr = np.zeros((3, 4))  # 3 rows, 4 columns
print(zero_arr)



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
#2. Ones Array (np.ones())
#Creates an array filled with ones.

ones_arr = np.ones((5,6))
print(ones_arr)



[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [1]:
#Identity Matrix (np.eye())
import numpy as np
#Creates an identity matrix (diagonal elements = 1, rest = 0).
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
#Diagonal Matrix (np.diag())
diag_matrix = np.diag([10, 20, 30,20])
print(diag_matrix)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 20]]


In [2]:
#Random Arrays (np.random)
#(a) Random Numbers Between 0 and 1 (np.random.rand())
import numpy as np
rand_arr = np.random.rand(3,3)
print(rand_arr)

[[0.88439429 0.28674727 0.15922791]
 [0.70451015 0.96292416 0.60105573]
 [0.41312409 0.59454806 0.73174852]]


In [4]:
#Random Integers (np.random.randint())

rand_ints = np.random.randint(100, 200, (3,5))  # 2x3 matrix with random numbers between 1-99
print(rand_ints)


[[145 145 113 128 177]
 [163 187 120 172 151]
 [146 118 108 139 186]]


In [30]:
#Arange Array (np.arange())
import numpy as np
#Creates an array with a range of values.
arr = np.arange(1, 12,2)  # Start=1, Stop=11, Step=2
print(arr)


[ 1  3  5  7  9 11]


In [6]:
# Linearly Spaced Array (np.linspace())
#numpy.linspace() is a function used to generate an array of evenly spaced numbers over a specified range.
#Creates an array with evenly spaced values between a range.
lin_arr = np.linspace(0, 100,5)  # 5 values between 0 and 10
print(lin_arr)

[  0.  25.  50.  75. 100.]


In [17]:
#Linear Algebra in NumPy
#NumPy provides a Linear Algebra module (numpy.linalg) that allows performing various matrix operations, including determinants, inverses, eigenvalues, and solving linear equations. It is highly optimized and widely used in machine learning, scientific computing, and data analysis.
#Most linear algebra functions are available under np.linalg.
#Matrix Operations
#(a) Matrix Multiplication (np.dot() or @ operator)

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

#  Using np.dot()
result = np.dot(A, B)

print(result)


[[19 22]
 [43 50]]


'Explanation: Standard matrix multiplication where\n(1*5 + 2*7, 1*6 + 2*8) = (19, 22)\n(3*5 + 4*7, 3*6 + 4*8) = (43, 50)'

In [21]:
#(b) Transpose of a Matrix (np.transpose() or .T)
A = np.array([[1, 2], [3, 4]])
#print(A)
print(A.T)  # Transpose using .T # Explanation: Rows become columns and vice versa.

[[1 3]
 [2 4]]


In [35]:
#(c) Determinant of a Matrix (np.linalg.det())    --> yha se chat gpt se dekho ki ye kese kam krta h 

#A = np.array([[1, 2,3], [3, 4,4],[3, 4,4]])
B=np.array([[2,2],[2,2]])
det = np.linalg.det(B) 
print(B)
print(det)

[[2 2]
 [2 2]]
0.0


In [68]:
#(d) Inverse of a Matrix (np.linalg.inv())

A = np.array([[1, 2], [3, 4]])
inverse = np.linalg.inv(A)
print(inverse)


1,2
3,4

# Explanation: The inverse of matrix A is A⁻¹, satisfying A × A⁻¹ = I (identity matrix).

[[-2.   1. ]
 [ 1.5 -0.5]]


In [69]:
#Eigenvalues and Eigenvectors
#Eigenvalues and eigenvectors are fundamental in machine learning and PCA (Principal Component Analysis).

A = np.array([[3, -2], [1, 0]])
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)


Eigenvalues: [2. 1.]
Eigenvectors: [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


' Explanation:\n\n    Eigenvalues measure how a matrix scales a vector.\n    Eigenvectors define the directions along which this scaling occurs.'

In [2]:
#Norm of a Matrix (np.linalg.norm())
#Computes the magnitude of a vector or matrix.
import numpy as np
A = np.array([3,4])
norm = np.linalg.norm(A)
print(norm)



5.0


'Explanation: Euclidean norm (L2 norm) is computed as:\n(3**2 + 4**2)underroot = 5\n'

In [3]:
#Rank of a Matrix (np.linalg.matrix_rank()) -> no. of unique elements in our matrix
A = np.array([[2,2], [2,1]])
rank = np.linalg.matrix_rank(A)
rank

#Explanation: The matrix has 2 linearly independent rows.

np.int64(2)

In [ ]:
'''Summary of NumPy Linear Algebra Functions
Function	Description
np.dot(A, B)	Matrix multiplication
A.T	Transpose of matrix A
np.linalg.det(A)	Determinant of matrix A
np.linalg.inv(A)	Inverse of matrix A
np.linalg.eig(A)	Eigenvalues & eigenvectors
np.linalg.norm(A)	Norm of a matrix/vector
np.linalg.matrix_rank(A)	Rank of matrix A'''

In [77]:
#Broadcasting in NumPy
#What is Broadcasting?
#Broadcasting is a NumPy feature that allows element-wise operations on arrays of different shapes without explicitly replicating smaller arrays. This makes computations faster and memory-efficient.

#Broadcasting Rules
#When performing operations between arrays of different shapes, NumPy applies broadcasting rules:

#If the arrays have the same shape, element-wise operations are performed normally.
#If the arrays have different shapes, NumPy tries to match the shapes by:
#Adding dimensions of size 1 where needed.
#Stretching (broadcasting) smaller arrays along those dimensions.

#Examples of Broadcasting
#1. Adding a Scalar to an Array
#A scalar (single number) is broadcasted to match the shape of an array

arr = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 10

result = arr + scalar  # Scalar is broadcasted
print(result)


[[11 12 13]
 [14 15 16]]


'Explanation:\nThe scalar 10 is added to each element in the array.'

In [78]:
#Adding a 1D Array to a 2D Array

arr2D = np.array([[1, 2, 3], [4, 5, 6]])
arr1D = np.array([10, 20, 30])

result = arr2D + arr1D
print(result)

'''Explanation:
The 1D array [10, 20, 30] is broadcasted row-wise across the 2D array.'''


[[11 22 33]
 [14 25 36]]


'Explanation:\nThe 1D array [10, 20, 30] is broadcasted row-wise across the 2D array.'

In [79]:
#Broadcasting in Multiplication

arr = np.array([[1], [2], [3]])  # Shape (3,1)
arr2 = np.array([10, 20, 30])    # Shape (1,3)

result = arr * arr2
print(result)


'''Explanation:

    The (3,1) array is stretched column-wise.
    The (1,3) array is stretched row-wise.'''

[[10 20 30]
 [20 40 60]
 [30 60 90]]


'Explanation:\n\n    The (3,1) array is stretched column-wise.\n    The (1,3) array is stretched row-wise.'

In [27]:
#when we deal with categorical or string type data
import numpy as np
arr = np.array(["apple", "mango", "banana",2,2])
print(arr)
print(arr.dtype)  # Checking the data type

['apple' 'mango' 'banana' '2' '2']
<U21
