                                                        NumPy At NetMax

In [2]:
import numpy as np
arr = np.array([[1,2,3,45,55]])
print(arr)

#shape gives us the shape,(row,cloumns and blocks) of the array
print(arr.shape)

#the ndim gives us the number of dimensions of the array
arr.ndim

[[ 1  2  3 45 55]]
(1, 5)


2

In [14]:
arr2d = np.array([[1,2,3,4,5],[6,7,8,9,0],[1,2,3,4,5]])
print(arr2d)
print(arr2d.ndim)
print(arr2d.shape)

[[1 2 3 4 5]
 [6 7 8 9 0]
 [1 2 3 4 5]]
2
(3, 5)


In [17]:
#3*3*1
arrtd = np.array([[[1],[2],[3]],[[6],[5],[4]],[[9],[10],[11]]])
print(arrtd)
print(arrtd.ndim)
print(arrtd.shape)

[[[ 1]
  [ 2]
  [ 3]]

 [[ 6]
  [ 5]
  [ 4]]

 [[ 9]
  [10]
  [11]]]
3
(3, 3, 1)


In [9]:
#reshaping an array
var = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

#keeping the product == number of elements, we can reshape the array

var2 = var.reshape(3,4)

#reshape returns a new array and does not modify the original array

print(var2)
print()

var3 = var2.reshape(2,2,3)

print(var3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [27]:
#Slicing and Indexing
var = np.array([1,2,3,4,5,6])
# print(var[3:6])

var2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

#akela : -> selects all values
print(var2[1:,1:]) #prints all row's first column




[[5 6]
 [8 9]]


In [29]:
x = np.array([[1,2,4,8],[9,10,20,30],[40,2,1,9],[0,3,5,2]])
print(x[1:3,2])

[20  1]


In [31]:
print(x[1:3,1:3])

[[10 20]
 [ 2  1]]


In [47]:
x3 = np.array([[[2,3],[4,5]],[[6,7],[8,9]],[[10,11],[12,13]]])
print(x3[1,0,1])
print("---------------------------------")
print(x3[1,1,:])
print("---------------------------------")
print(x3[:,1,:])
print("---------------------------------")
print(x3[0:3,1,0:2])
print("---------------------------------")
print(x3[0:2,0,:])
print("---------------------------------")





7
---------------------------------
[8 9]
---------------------------------
[[ 4  5]
 [ 8  9]
 [12 13]]
---------------------------------
[[ 4  5]
 [ 8  9]
 [12 13]]
---------------------------------
[[2 3]
 [6 7]]
---------------------------------
[[[10 11]
  [12 13]]]


In [57]:
#Q. make a two dimensional array, 
test = np.array([[1,3,4],[8,2,9],[10,14,15]])
print(test[1,1:])
print(test[:,1])
print(test[1:,1:])
print(test[0:2,0])
print(test[2,0:2])

[2 9]
[ 3  2 14]
[[ 2  9]
 [14 15]]
[1 8]
[10 14]


In [62]:
#test a 3d array
test3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(test3[0,1,:])
print(test3[1,:,0])
print(test3[:,1,:])

[3 4]
[5 7]
[[3 4]
 [7 8]]


In [63]:
test3 = test3*4
print(test3)

[[[ 4  8]
  [12 16]]

 [[20 24]
  [28 32]]]


In [67]:
a = np.array([1,2,3])
b = np.array([3,2,1])

c = a+b
print(c)


[4 4 4]


numpy.ndarray

Special Type of arrays in numpy
    .array with zeros
    .array with ones
    .empty array
    .linespace error
    .random array

Hint -> For operation on rows x = 0;
        For operation on coumns x = 1;



In [4]:
import numpy as np
x = np.array([[1,4,2],[2,9,18],[20,4,14]])
print(np.sort(x,0)) # sort each row 
print(np.sort(x,1)) # sort each column

[[ 1  4  2]
 [ 2  4 14]
 [20  9 18]]
[[ 1  2  4]
 [ 2  9 18]
 [ 4 14 20]]


In [2]:
import numpy as np
a1 = np.array([[1,2],[3,4],[5,6],[7,8]])
print(a1)
a2 = np.array([[[1],[2],[3],[4]],[[4],[3],[2],[1]],[[1],[2],[3],[4]],[[4],[3],[2],[1]]])
print(a2)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1]
  [2]
  [3]
  [4]]

 [[4]
  [3]
  [2]
  [1]]

 [[1]
  [2]
  [3]
  [4]]

 [[4]
  [3]
  [2]
  [1]]]


In [5]:
#updating elements
x = np.array([1,2,4,5])
x[1] = 100
print(x)

d2 = np.array([[1,2,3],[4,5,6]])
d2[1][1] = 200
d2[1,1] = 2000
print(d2)

[  1 100   4   5]
[[   1    2    3]
 [   4 2000    6]]


In [12]:
#how to add row and column to a 2D array
x1 = np.array([1,2,4,5])

#insert at last
var = np.append(x1,6)

#insert at a given index
var = np.insert(x1,0,100)
print(var)

#adding element to 1D array
#axis = 0 -> row wise operation
#axis =1 -> column wise operation

d3 = np.array([[1,2,3],[4,5,6]])

[100   1   2   4   5]


In [6]:
d2 = np.array([[1,2,3],[4,5,6]])
#insertion in 2D
test = np.insert(d2,1,[[1,2,3]],axis = 0)
print(test)

column = np.insert(d2,3,[[2],[1]],axis =1)
print(column)


[[1 2 3]
 [1 2 3]
 [4 5 6]]
[[1 2 3 2 1]
 [4 5 6 2 1]]


In [35]:
#delete
test = [1,2,3,4]
# 2nd argument is index
n = np.delete(test,0)
n

#delete in 2d array
d2 = np.array([[1,2,3],[4,5,6]])

# see how changing the axis changes what gets deleted
''' SINGLE ELEMENT CANNOT BE DELETED FROM MULTI-DIMENSIONAL ARRAY'''

var = np.delete(d2,0,axis = 1)
var


array([[2, 3],
       [5, 6]])

Scaler -> scale up or scale down the matrix


In [38]:
d2 = np.array([[1,2,3],[4,5,6],[8,9,10],[11,23,44]])
d2 += 5 #back of the code, the addition gets broadcasted to all the elements
d2

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [13, 14, 15],
       [16, 28, 49]])

In [ ]:
                                                    Special Types of arrays

In [9]:
#array with all zeros
#NOTE -> 

one = np.ones((3,3))
one
zeros = np.zeros((3,4,5))
print(zeros)
print(type(one[0,0]))

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
<class 'numpy.float64'>


In [8]:
import numpy as np
arr2d = np.array([[1,2,3,4,5],[6,7,8,9,0],[1,2,3,4,5]])
arr = np.array([1,2,3,4,5])
print(arr+arr2d)

[[ 2  4  6  8 10]
 [ 7  9 11 13  5]
 [ 2  4  6  8 10]]


Identity Matrix
Random Matrix (random.rand ; random.randit ; 
Digonal Matrix
arange
linespace
.dot product (np.dot(matrixA, matrixB))
Transpose of matrix(interchange rows x columns)
Determininat(np.linalg.det(matrix))
Inverse of matrix
Eigen values and eigen vectors
Normalization of matrix 
Rank of Matrix


