Numpy is a python library to create multi-dimensional arrays.
    1. Python list are slower
    2. as Numpy uses fixed type so it is faster
    3. The dynamic type of List makes its size unnecassay larger
    4. Used is used in AI ML as it is strict and fast
    

In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [16]:
# declaring and initializing an array in numpy
import numpy as na

a = na.array([1,2,4,55])

print(a)






[ 1  2  4 55]


In [5]:
b = na.array([[1.2,5.2],[1.0, 55.2]])
print(b)

[[ 1.2  5.2]
 [ 1.  55.2]]


In [14]:
#how to get dimension of numpy
# a.ndim 
print(a.ndim)
b.ndim

1


2

In [20]:
#get shape (How many rows and cloumns)
print(a.shape)
print(b.shape)

(4,)
(2, 2)


In [23]:
a.shape
b.shape

(2, 2)

In [31]:
print(a.dtype)
print(a.itemsize)
# we can also define a datatype while initialization
c = na.array([1,2,4,5,6,7,44], dtype = 'int16')
print(c)
print(c.dtype)

# getting size of each item
print(c.itemsize)

int64
8
[ 1  2  4  5  6  7 44]
int16
2


In [32]:
#total elements
print(c.size)

7


In [37]:
print(b[0][0].nbytes) # how many bytes each element occupies

8


Update and Delete in Numpy Array


In [42]:
tn = na.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]], dtype='int32')
print(tn)
print(tn.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 7)


In [49]:
#Get specific element
print(tn[0][2])
#in numpy we can also use the format
print(tn[-1,2])



3
10
[ 8  9 10 11 12 13 14]


In [53]:
# how to get a specific row
print(tn[1, :])
print(tn[:,4])

# for reference this is the same notation as in python string
print(tn[1, 1:5])

[ 8  9 10 11 12 13 14]
[ 5 12]
[ 9 10 11 12]


In [54]:
# [start index, end index, step]
print(tn[0, 1:6:2])

[2 4 6]


In [57]:
# update
tn[0,0] = 12
print(tn)

[[12  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [58]:
tn(:, 1) = 5
print(tn)

SyntaxError: invalid syntax (156783785.py, line 1)