1. An element in the python list :
    Size - 4 B
    Object value - 8 B
    Object Type - 8 B
    Reference count - 8 B
so each element is 28 bytes long
This increases the space complexity

while in numpy array element is just equal to the size of its data type

2. Element is list store referneces so an overhead is expected when we try to access the actual data makeing the traversal and serach operations slow

3. The hetrogeneous nature of list makes increases overhead as time is spend analysing the data type

In [ ]:
''' Observation:
the axis value denotes (in 2D)
    0 = row
    1 = column 
in 3D
    0 = block
    1 = row
    2 = column

the axis value denotes which of (row, column, block) can be updated
'''



In [28]:
import numpy as np
d2 = np.array([[1,2,3],[1,2,3],[1,2,3]])
var = d2.flatten()
var
x = np.array([[1,4,2],[2,9,18],[20,4,14]])
test = np.append(x,[[1],[2],[3]], axis = 1)
test
arrtd = np.array([[[1,1,1],[2,2,2],[3,3,3]],[[6,6,6],[5,5,5],[4,4,4]],[[9,9,9],[10,10,10],[11,11,11]]])
xz = np.append(arrtd,[[[0,0,0]],[[0,0,0]],[[0,0,0]]], axis = 1)
print(xz)
z = np.append(arrtd,[[[4],[4],[4]],[[4],[4],[4]],[[4],[4],[4]]], axis =2)
z

[[[ 1  1  1]
  [ 2  2  2]
  [ 3  3  3]
  [ 0  0  0]]

 [[ 6  6  6]
  [ 5  5  5]
  [ 4  4  4]
  [ 0  0  0]]

 [[ 9  9  9]
  [10 10 10]
  [11 11 11]
  [ 0  0  0]]]


array([[[ 1,  1,  1,  4],
        [ 2,  2,  2,  4],
        [ 3,  3,  3,  4]],

       [[ 6,  6,  6,  4],
        [ 5,  5,  5,  4],
        [ 4,  4,  4,  4]],

       [[ 9,  9,  9,  4],
        [10, 10, 10,  4],
        [11, 11, 11,  4]]])